-- Persist a tenant-scoped, privacy-safe receipt for every ActionPlan
-- transition.  This is deliberately separate from admin_audit_logs: the
-- actor is an ordinary user, and the record is an operational trace rather
-- than an administrative decision log.

ALTER TABLE agent_action_plans
    ADD COLUMN IF NOT EXISTS result_code TEXT;

UPDATE agent_action_plans
SET result_code = CASE status
    WHEN 'executed' THEN 'executed'
    WHEN 'failed' THEN 'execution_failed'
    WHEN 'cancelled' THEN 'cancelled'
    WHEN 'expired' THEN 'expired'
    WHEN 'interrupted' THEN 'interrupted'
    ELSE result_code
END
WHERE result_code IS NULL;

ALTER TABLE agent_action_plans
    DROP CONSTRAINT IF EXISTS agent_action_plans_result_code_check;

ALTER TABLE agent_action_plans
    ADD CONSTRAINT agent_action_plans_result_code_check CHECK (
        result_code IS NULL
        OR result_code IN (
            'executed', 'execution_failed', 'cancelled', 'expired',
            'interrupted'
        )
    );

COMMENT ON COLUMN agent_action_plans.result_code IS
    'Stable machine-readable terminal outcome; result remains a human-facing summary';

CREATE TABLE IF NOT EXISTS agent_action_audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trace_id TEXT NOT NULL CHECK (char_length(trace_id) BETWEEN 1 AND 128),
    campus_id UUID NOT NULL REFERENCES campuses(id),
    user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    plan_id UUID REFERENCES agent_action_plans(id) ON DELETE SET NULL,
    action TEXT,
    risk_level TEXT CHECK (risk_level IS NULL OR risk_level IN ('L2', 'L3')),
    event_type TEXT NOT NULL CHECK (event_type IN (
        'proposal_created',
        'proposal_replayed',
        'proposal_conflict',
        'first_confirmation',
        'second_confirmation_requested',
        'confirmation_rejected',
        'execution_started',
        'execution_succeeded',
        'execution_failed',
        'already_executed',
        'expired',
        'cancelled'
    )),
    outcome_code TEXT NOT NULL CHECK (outcome_code IN (
        'pending',
        'reused',
        'idempotency_conflict',
        'needs_second_confirmation',
        'invalid_token',
        'not_found',
        'not_confirmable',
        'executing',
        'executed',
        'execution_failed',
        'already_executed',
        'expired',
        'cancelled'
    )),
    duration_ms INTEGER CHECK (duration_ms IS NULL OR duration_ms >= 0),
    -- Metadata is generated by the service from a fixed allow-list.  Keep a
    -- hard size ceiling so a future caller cannot turn this into a body dump.
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (pg_column_size(metadata) <= 4096),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_action_audits_user_created
    ON agent_action_audits (campus_id, user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_agent_action_audits_plan_created
    ON agent_action_audits (campus_id, plan_id, created_at DESC)
    WHERE plan_id IS NOT NULL;

-- Add the same defense-in-depth tenant policy as the other user-owned facts.
ALTER TABLE agent_action_audits ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_action_audits FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_action_audits;
CREATE POLICY tenant_isolation ON agent_action_audits
    USING (
        current_setting('app.campus_id', true) IS NULL
        OR current_setting('app.campus_id', true) = ''
        OR campus_id = current_setting('app.campus_id', true)::uuid
    )
    WITH CHECK (
        current_setting('app.campus_id', true) IS NULL
        OR current_setting('app.campus_id', true) = ''
        OR campus_id = current_setting('app.campus_id', true)::uuid
    );

COMMENT ON TABLE agent_action_audits IS
    'Privacy-safe user-scoped ActionPlan receipts; never store message bodies, tokens, or full error text';
